include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**
  errors:
    public_member_api_docs: ignore

linter:
  rules:
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    sort_constructors_first: false
